CREATE TABLE OPERADOR(
    Id int PRIMARY KEY,
    Nombre varchar(255) NOT NULL,
    Tipo varchar(255),
    TelefonoContacto int
)

CREATE TABLE EMPRESA(
    Id_operador int PRIMARY KEY,
    Rut int NOT NULL,
    Rst int NOT NULL,
    Tipo varchar(255)
)

CREATE TABLE HOSPEDAJE (
    Id int PRIMARY KEY,
    Tipo varchar(255) NOT NULL
)

CREATE TABLE SERVICIO(
    ID int PRIMARY KEY,
    TIPOSERVICIO varchar(20) NOT NULL,
    CARGOADICIONAL int not null,
    DESCRIPCION varchar(255) NOT NULL,
    ID_HOSPEDAJE int NOT NULL
)

CREATE TABLE HABITACIONHOTEL(
ID_HOSPEDAJE int PRIMARY KEY,
TIPOHABITACION varchar(20) not null,
COSTOPORNOCHE int not null,
CATEGORIAINSTALACION int,
NUMEROHABITACION varchar(10) not null,
CAPACIDAD int,
ID_HOTEL int not null
)

CREATE TABLE VIVIENDA(
ID_HOSPEDAJE int PRIMARY KEY,
CANTIDADHABITACIONES int,
UBICACION varchar(255),
MENAJE varchar(255),
COSTOPORNOCHE int,
ASEGURADORA varchar(255),
TIPOSEGURO varchar(255),
ID_PERSONA int not null
)

CREATE TABLE HABITACIONHOSTAL(
ID_HOSPEDAJE int PRIMARY KEY,
CAPACIDAD int,
COSTOPORNOCHE int,
ID_HOSTAL int
)

CREATE TABLE OPERADOR(
    Id int PRIMARY KEY,
    Nombre varchar(255) NOT NULL,
    Tipo varchar(255),
    TelefonoContacto int
)

CREATE TABLE EMPRESA(
    Id_operador int PRIMARY KEY,
    Rut int NOT NULL,
    Rst int NOT NULL,
    Tipo varchar(255)
)

CREATE TABLE HOSPEDAJE (
    Id int PRIMARY KEY,
    Tipo varchar(255) NOT NULL
)

CREATE TABLE SERVICIO(
    ID int PRIMARY KEY,
    TIPOSERVICIO varchar(20) NOT NULL,
    CARGOADICIONAL int not null,
    DESCRIPCION varchar(255) NOT NULL,
    ID_HOSPEDAJE int NOT NULL
)

CREATE TABLE HABITACIONHOTEL(
ID_HOSPEDAJE int PRIMARY KEY,
TIPOHABITACION varchar(20) not null,
COSTOPORNOCHE int not null,
CATEGORIAINSTALACION int,
NUMEROHABITACION varchar(10) not null,
CAPACIDAD int,
ID_HOTEL int not null
)

CREATE TABLE VIVIENDA(
ID_HOSPEDAJE int PRIMARY KEY,
CANTIDADHABITACIONES int,
UBICACION varchar(255),
MENAJE varchar(255),
COSTOPORNOCHE int,
ASEGURADORA varchar(255),
TIPOSEGURO varchar(255),
ID_PERSONA int not null
)

CREATE TABLE HABITACIONHOSTAL(
ID_HOSPEDAJE int PRIMARY KEY,
CAPACIDAD int,
COSTOPORNOCHE int,
ID_HOSTAL int
)